run:
  timeout: 5m

output:
  formats:
    - format: junit-xml
      path: report.xml
    - format: colored-tab
      path: stdout

linters:
  enable:
    # Defaults
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Extra https://golangci-lint.run/usage/linters/#disabled-by-default
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    # - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - fatcontext
    # - forbidigo
    - forcetypeassert
    # - funlen
    # - gci
    # - ginkgolinter
    - gocheckcompilerdirectives
    # - gochecknoglobals
    # - gochecknoinits
    # - gochecksumtype
    - gocognit
    - goconst
    - gocritic # TODO: Configure
    - gocyclo
    - gofmt # TODO: Configure
    - goheader
    - goimports
    - gomoddirectives
    - goprintffuncname
    # - gosec
    - gosmopolitan
    - grouper
    - importas
    - inamedparam
    - interfacebloat
    - intrange
    - ireturn
    - lll # TODO: Configure
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - mnd
    - misspell
    # - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    # - noctx
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    # - perfsprint
    # - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    # - revive
    # - rowserrcheck
    - sloglint
    # - spancheck
    # - sqlclosecheck
    # - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    # - testableexamples
    - testifylint
    # - testpackage
    # - thelper
    # - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    # - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl # TODO: Configure
    - zerologlint

linters-settings:
  tagliatelle:
    case:
      rules:
        yaml: snake
        bson: snake
        json: snake
